### ISSUE TITLE
Is Documenter a required dependency for this package?

### ISSUE THREAD

**Issue by navidcy** [rjdverbeek-tud/SphericalGeometry.jl#10]
Seems odd. Is this on purpose?

https://github.com/rjdverbeek-tud/SphericalGeometry.jl/blob/30ef7252264d438b33e78ccfdab61520114e5d60/Project.toml#L7

**Comment by rjdverbeek-tud** [comment]
Sorry, I am not that fluent with properly distributing packages

Op wo 26 apr. 2023 00:26 schreef Navid C. Constantinou <
***@***.***>:

**Comment by navidcy** [comment]
I made a PR ghat deals w it. No need for apologies. Was just wondering if it was on purpose.
