### ISSUE TITLE
Convention of latitude and longitude

### ISSUE THREAD

**Issue by ChiMaoShuPhy** [rjdverbeek-tud/SphericalGeometry.jl#12]
Could you please explain the convention of latitude and longitude used in this package? For example, their relation to polar angle $\theta$ and azimuthal angle $\phi$ in the spherical coordinate system as shown in this picture. 

[https://en.wikipedia.org/wiki/File:3D_Spherical.svg](url)

![2023-08-07_11-19](https://github.com/rjdverbeek-tud/SphericalGeometry.jl/assets/16471347/34a78832-3e8e-431b-a189-1b989f482796)

**Comment by rjdverbeek-tud** [comment]
I have added the convention to the readme. I use the Geographic Coordinate System
